# File: .github/workflows/workflow.yml
on: [push]

name: example

jobs:

  devflow:
    runs-on: ubuntu-latest
    steps:
    
    - uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: "Activate Namespace"
      uses: okteto/namespace@latest
      with:
        name: williamdtorres
    
    - name: "Deploy application"
      uses: okteto/apply@latest
      with:
        namespace: williamdtorres
        manifest: k8s.yml

    - name: "Push changes"
      uses: okteto/push@latest
      with:
        namespace: williamdtorres
        name: hello-world
